[project]
name = "finance-management-system"
version = "0.1.0"
description = "This is the backend webserver for the FMS project."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.1.6",
    "django-cors-headers>=4.7.0",
    "djangorestframework>=3.16.0",
]
