# Generated by Django 5.1.6 on 2025-04-24 02:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_remove_transaction_date_transaction_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='authorized_users',
            field=models.ManyToManyField(blank=True, related_name='authorized_accounts', to='ledger.user'),
        ),
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
